#python3 test.py -n simple/1/cifar10/$1/ -m deep_ensembles_models/simple/1/cifar10/cifar10 -d cifar10 -nd mnist -nn 1
#python3 test.py -n simple/1/cifar10/$1/ -m deep_ensembles_models/simple/1/cifar10/cifar10 -d cifar10 -nd fashion -nn 1
#python3 test.py -n simple/2/cifar10/$1/ -m deep_ensembles_models/simple/2/cifar10/cifar10 -d cifar10 -nd mnist -nn 2
#python3 test.py -n simple/2/cifar10/$1/ -m deep_ensembles_models/simple/2/cifar10/cifar10 -d cifar10 -nd fashion -nn 2
#python3 test.py -n simple/3/cifar10/$1/ -m deep_ensembles_models/simple/3/cifar10/cifar10 -d cifar10 -nd mnist -nn 3
#python3 test.py -n simple/3/cifar10/$1/ -m deep_ensembles_models/simple/3/cifar10/cifar10 -d cifar10 -nd fashion -nn 3
#python3 test.py -n simple/4/cifar10/$1/ -m deep_ensembles_models/simple/4/cifar10/cifar10 -d cifar10 -nd mnist -nn 4
#python3 test.py -n simple/4/cifar10/$1/ -m deep_ensembles_models/simple/4/cifar10/cifar10 -d cifar10 -nd fashion -nn 4
#python3 test.py -n simple/5/cifar10/$1/ -m deep_ensembles_models/simple/5/cifar10/cifar10 -d cifar10 -nd mnist -nn 5
#python3 test.py -n simple/5/cifar10/$1/ -m deep_ensembles_models/simple/5/cifar10/cifar10 -d cifar10 -nd fashion -nn 5
#python3 test.py -n simple/6/cifar10/$1/ -m deep_ensembles_models/simple/6/cifar10/cifar10 -d cifar10 -nd mnist -nn 6
#python3 test.py -n simple/6/cifar10/$1/ -m deep_ensembles_models/simple/6/cifar10/cifar10 -d cifar10 -nd fashion -nn 6
#python3 test.py -n simple/7/cifar10/$1/ -m deep_ensembles_models/simple/7/cifar10/cifar10 -d cifar10 -nd mnist -nn 7
#python3 test.py -n simple/7/cifar10/$1/ -m deep_ensembles_models/simple/7/cifar10/cifar10 -d cifar10 -nd fashion -nn 7
#python3 test.py -n simple/8/cifar10/$1/ -m deep_ensembles_models/simple/8/cifar10/cifar10 -d cifar10 -nd mnist -nn 8
#python3 test.py -n simple/8/cifar10/$1/ -m deep_ensembles_models/simple/8/cifar10/cifar10 -d cifar10 -nd fashion -nn 8
#python3 test.py -n simple/9/cifar10/$1/ -m deep_ensembles_models/simple/9/cifar10/cifar10 -d cifar10 -nd mnist -nn 9
#python3 test.py -n simple/9/cifar10/$1/ -m deep_ensembles_models/simple/9/cifar10/cifar10 -d cifar10 -nd fashion -nn 9
#python3 test.py -n simple/10/cifar10/$1/ -m deep_ensembles_models/simple/10/cifar10/cifar10 -d cifar10 -nd mnist -nn 10
#python3 test.py -n simple/10/cifar10/$1/ -m deep_ensembles_models/simple/10/cifar10/cifar10 -d cifar10 -nd fashion -nn 10

#python3 test.py -n simple/1/mnist/$1/ -m deep_ensembles_models/simple/1/mnist/mnist -d mnist -nd cifar10 -nn 1
python3 test.py -n simple/1/mnist/$1/ -m deep_ensembles_models/simple/1/mnist/mnist -d mnist -nd fashion -nn 1
#python3 test.py -n simple/2/mnist/$1/ -m deep_ensembles_models/simple/2/mnist/mnist -d mnist -nd cifar10 -nn 2
python3 test.py -n simple/2/mnist/$1/ -m deep_ensembles_models/simple/2/mnist/mnist -d mnist -nd fashion -nn 2
#python3 test.py -n simple/3/mnist/$1/ -m deep_ensembles_models/simple/3/mnist/mnist -d mnist -nd cifar10 -nn 3
python3 test.py -n simple/3/mnist/$1/ -m deep_ensembles_models/simple/3/mnist/mnist -d mnist -nd fashion -nn 3
#python3 test.py -n simple/4/mnist/$1/ -m deep_ensembles_models/simple/4/mnist/mnist -d mnist -nd cifar10 -nn 4
python3 test.py -n simple/4/mnist/$1/ -m deep_ensembles_models/simple/4/mnist/mnist -d mnist -nd fashion -nn 4
#python3 test.py -n simple/5/mnist/$1/ -m deep_ensembles_models/simple/5/mnist/mnist -d mnist -nd cifar10 -nn 5
python3 test.py -n simple/5/mnist/$1/ -m deep_ensembles_models/simple/5/mnist/mnist -d mnist -nd fashion -nn 5
#python3 test.py -n simple/6/mnist/$1/ -m deep_ensembles_models/simple/6/mnist/mnist -d mnist -nd cifar10 -nn 6
python3 test.py -n simple/6/mnist/$1/ -m deep_ensembles_models/simple/6/mnist/mnist -d mnist -nd fashion -nn 6
#python3 test.py -n simple/7/mnist/$1/ -m deep_ensembles_models/simple/7/mnist/mnist -d mnist -nd cifar10 -nn 7
python3 test.py -n simple/7/mnist/$1/ -m deep_ensembles_models/simple/7/mnist/mnist -d mnist -nd fashion -nn 7
#python3 test.py -n simple/8/mnist/$1/ -m deep_ensembles_models/simple/8/mnist/mnist -d mnist -nd cifar10 -nn 8
python3 test.py -n simple/8/mnist/$1/ -m deep_ensembles_models/simple/8/mnist/mnist -d mnist -nd fashion -nn 8
#python3 test.py -n simple/9/mnist/$1/ -m deep_ensembles_models/simple/9/mnist/mnist -d mnist -nd cifar10 -nn 9
python3 test.py -n simple/9/mnist/$1/ -m deep_ensembles_models/simple/9/mnist/mnist -d mnist -nd fashion -nn 9
#python3 test.py -n simple/10/mnist/$1/ -m deep_ensembles_models/simple/10/mnist/mnist -d mnist -nd cifar10 -nn 10
python3 test.py -n simple/10/mnist/$1/ -m deep_ensembles_models/simple/10/mnist/mnist -d mnist -nd fashion -nn 10

python3 test.py -n simple/1/fashion/$1/ -m deep_ensembles_models/simple/1/fashion/fashion -d fashion -nd mnist -nn 1
#python3 test.py -n simple/1/fashion/$1/ -m deep_ensembles_models/simple/1/fashion/fashion -d fashion -nd cifar10 -nn 1
python3 test.py -n simple/2/fashion/$1/ -m deep_ensembles_models/simple/2/fashion/fashion -d fashion -nd mnist -nn 2
#python3 test.py -n simple/2/fashion/$1/ -m deep_ensembles_models/simple/2/fashion/fashion -d fashion -nd cifar10 -nn 2
python3 test.py -n simple/3/fashion/$1/ -m deep_ensembles_models/simple/3/fashion/fashion -d fashion -nd mnist -nn 3
#python3 test.py -n simple/3/fashion/$1/ -m deep_ensembles_models/simple/3/fashion/fashion -d fashion -nd cifar10 -nn 3
python3 test.py -n simple/4/fashion/$1/ -m deep_ensembles_models/simple/4/fashion/fashion -d fashion -nd mnist -nn 4
#python3 test.py -n simple/4/fashion/$1/ -m deep_ensembles_models/simple/4/fashion/fashion -d fashion -nd cifar10 -nn 4
python3 test.py -n simple/5/fashion/$1/ -m deep_ensembles_models/simple/5/fashion/fashion -d fashion -nd mnist -nn 5
#python3 test.py -n simple/5/fashion/$1/ -m deep_ensembles_models/simple/5/fashion/fashion -d fashion -nd cifar10 -nn 5
python3 test.py -n simple/6/fashion/$1/ -m deep_ensembles_models/simple/6/fashion/fashion -d fashion -nd mnist -nn 6
#python3 test.py -n simple/6/fashion/$1/ -m deep_ensembles_models/simple/6/fashion/fashion -d fashion -nd cifar10 -nn 6
python3 test.py -n simple/7/fashion/$1/ -m deep_ensembles_models/simple/7/fashion/fashion -d fashion -nd mnist -nn 7
#python3 test.py -n simple/7/fashion/$1/ -m deep_ensembles_models/simple/7/fashion/fashion -d fashion -nd cifar10 -nn 7
python3 test.py -n simple/8/fashion/$1/ -m deep_ensembles_models/simple/8/fashion/fashion -d fashion -nd mnist -nn 8
#python3 test.py -n simple/8/fashion/$1/ -m deep_ensembles_models/simple/8/fashion/fashion -d fashion -nd cifar10 -nn 8
python3 test.py -n simple/9/fashion/$1/ -m deep_ensembles_models/simple/9/fashion/fashion -d fashion -nd mnist -nn 9
#python3 test.py -n simple/9/fashion/$1/ -m deep_ensembles_models/simple/9/fashion/fashion -d fashion -nd cifar10 -nn 9
python3 test.py -n simple/10/fashion/$1/ -m deep_ensembles_models/simple/10/fashion/fashion -d fashion -nd mnist -nn 10
#python3 test.py -n simple/10/fashion/$1/ -m deep_ensembles_models/simple/10/fashion/fashion -d fashion -nd cifar10 -nn 10
